# Generated by Django 6.0.1 on 2026-02-19 07:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0002_location"),
    ]

    operations = [
        migrations.CreateModel(
            name="BusStop",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_stop_number", models.TextField()),
                ("bus_stop_name", models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name="BusService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("service_number", models.TextField()),
                ("arrival_time", models.DateTimeField()),
                ("next_arrival_time", models.DateTimeField()),
                (
                    "busstop",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="bussservice",
                        to="persons.busstop",
                    ),
                ),
            ],
        ),
    ]
