# Generated by Django 6.0.1 on 2026-02-19 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0003_busstop_busservice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="busservice",
            name="arrival_time",
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name="busservice",
            name="next_arrival_time",
            field=models.TextField(),
        ),
    ]
