# Generated by Django 6.0.1 on 2026-02-21 04:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0004_alter_busservice_arrival_time_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Bus",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("bus_stopno", models.TextField()),
                ("bus_serviceno", models.TextField()),
                ("arrival_time", models.TimeField()),
            ],
        ),
    ]
