# Generated by Django 6.0.1 on 2026-02-21 09:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("persons", "0005_bus"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="bus",
            name="bus_stopno",
        ),
        migrations.AddField(
            model_name="bus",
            name="busstop",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="persons.busstop",
            ),
        ),
    ]
